In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats
from itertools import product

import matplotlib.pyplot as plt
%matplotlib inline

# 빅데이터 개론 정리(중간 이후)
> 11월 1일 ~

- toc: true 
- badges: true
- comments: true
- author : 김혜지
- categories: [python]

# 함수


## np

In [3]:
np.sqrt(2)

1.4142135623730951

In [5]:
np.log(10)

2.302585092994046

In [7]:
np.sin(3)

0.1411200080598672

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(10,20,0.5)

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [11]:
a = np.arange(10)

In [12]:
max(a), np.max(a)

(9, 9)

In [13]:
sum(a), np.sum(a)

(45, 45)

In [14]:
np.mean(a)

4.5

In [16]:
np.cumsum(a) # x 의 원소들의 누적합(cumulative sum)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

## 함수 만들기

### 숫자 벡터 또는 리스트에 있는 양수들의 합

In [18]:
my_numbers = np.arange(-10,10)

my_sum = 0
for value in my_numbers :
  if value > 0 :
    my_sum = my_sum + value

my_sum

45